logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.example.eccomerce: INFO

spring:
  application:
    name: eccomerce

  threads:
    virtual:
      enable: true

  data:
    jpa:
      repositories:
        bootstrap-mode: deferred

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: eccomerce
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver


  liquibase:
    enable: false
    change-log: classpath:db/changelog/master.xml
    default-schema: eccomerce
    contexts: dev

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri:
#          jwk-set-uri:
#          audiences:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB